sonar.projectKey=Miraclewills_cloud-event-management-system
sonar.organization=miraclewills
sonar.sources=.
sonar.exclusions=**/migrations/**,**/staticfiles/**,**/__pycache__/**,**/static/**
sonar.python.version=3.9
sonar.python.coverage.reportPaths=coverage.xml
